# Q 1: Create variables for storing a person's name, age, and average test score.

name = "Pradyumna"
age = 28
avarage_test = 85.6
# Q 2: Concatenate two strings and print the result.
First_name = "Pradyumna"
last_name = "Das"
full_name = First_name + " "+ last_name
print(full_name)

# Q 3: Create a list of fruits and access elements using indexing. 
fruits = ["apple", "grapes", "banana", "pinaple"]
print(fruits[0])
print(fruits[1])
print(fruits[2])
print(fruits[3])